"""Shared constants and limits."""

from enum import IntEnum

PREFIXES = ("pl!", "plurality!")
MENTION_PREFIX = True

MAX_PROXY_NAME_LENGTH = 80
MAX_SYSTEM_NAME_LENGTH = 100
MAX_SYSTEM_TAG_LENGTH = 79
MAX_MEMBER_COUNT = 100_000
MAX_GROUP_COUNT = 5_000
MAX_DESCRIPTION_LENGTH = 1024
MAX_MEMBER_NAME_LENGTH = 100
MAX_GROUP_NAME_LENGTH = 100
MAX_PRONOUNS_LENGTH = 100
MAX_URI_LENGTH = 256
MAX_MESSAGE_LENGTH = 2000
MAX_ATTACHMENTS_PER_MESSAGE = 10
MAX_ATTACHMENT_CHUNK_BYTES = 8 * 1024 * 1024
AVATAR_FILE_SIZE_LIMIT = 1024 * 1024

AUTOPROXY_ESCAPE = "\\"
LATCH_EXPIRY_HOURS = 10 * 365 * 24  # effectively never, matching PK

EMBED_COLOR = 0x7B68EE  # medium slate blue
SUCCESS_EMOJI = "✅"
ERROR_EMOJI = "❌"
NOTE_EMOJI = "ℹ️"


class PrivacyLevel(IntEnum):
    PRIVATE = 1
    PUBLIC = 2


class AutoproxyMode(IntEnum):
    OFF = 0
    FRONT = 1
    LATCH = 2
    MEMBER = 3